# Generated by Django 4.0.4 on 2022-05-22 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=3)),
                ('nama', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=1)),
                ('alamat', models.TextField()),
                ('email', models.CharField(max_length=45)),
                ('foto', models.CharField(blank=True, max_length=45, null=True)),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectapp.divisi')),
            ],
        ),
    ]
