# Generated by Django 4.0.4 on 2022-05-22 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_jabatan_pegawai_jabatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawai',
            name='divisi',
        ),
        migrations.RemoveField(
            model_name='pegawai',
            name='jabatan',
        ),
        migrations.DeleteModel(
            name='Divisi',
        ),
        migrations.DeleteModel(
            name='Jabatan',
        ),
        migrations.DeleteModel(
            name='Pegawai',
        ),
    ]
